# Generated by Django 4.1.5 on 2023-02-01 19:09

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import members.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Event1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("fee", models.IntegerField(default=200)),
            ],
        ),
        migrations.CreateModel(
            name="Event2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("fee", models.IntegerField(default=200)),
            ],
        ),
        migrations.CreateModel(
            name="Workshop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("name", ckeditor.fields.RichTextField()),
                ("fee", models.IntegerField()),
                ("desc", ckeditor.fields.RichTextField(blank=True, null=True)),
                ("organised_at", models.DateTimeField(blank=True, null=True)),
                ("conducted_by", ckeditor.fields.RichTextField(blank=True, null=True)),
                ("link", models.URLField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="WorkshopBio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("text", ckeditor.fields.RichTextField(blank=True, null=True)),
                ("total", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "razorpay_payment_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "dept",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.dept",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workshop",
                    models.ManyToManyField(
                        blank=True, null=True, to="members.workshop"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institute", models.CharField(max_length=50)),
                (
                    "abstract",
                    models.FileField(upload_to=members.models.content_file_name),
                ),
                (
                    "abstractFormat",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                (
                    "number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("text", ckeditor.fields.RichTextField(blank=True, null=True)),
                ("total", models.IntegerField(blank=True, default=0, null=True)),
                ("selected", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "selected_oral",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "razorpay_payment_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "iitg_student",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "dept",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.dept",
                    ),
                ),
                (
                    "event1",
                    models.ManyToManyField(blank=True, null=True, to="members.event1"),
                ),
                (
                    "event2",
                    models.ForeignKey(
                        default=3,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.event2",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
