# Generated by Django 3.2.8 on 2021-11-02 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='event2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.event2'),
        ),
    ]
