# Generated by Django 3.2.8 on 2021-11-07 06:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rename_paid_bio_ready_for_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
