# Generated by Django 3.2.8 on 2021-11-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_workshop_workshopbio'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
