# Generated by Django 3.2.8 on 2021-11-15 04:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_bio_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='conducted_by',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='organised_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
