# Generated by Django 3.2.8 on 2021-11-15 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20211115_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='event2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.event2'),
        ),
    ]
