# Generated by Django 3.2.8 on 2021-11-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_bio_event2'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
