# Generated by Django 3.2.8 on 2021-11-17 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_alter_bio_event2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='event2',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='members.event2'),
        ),
    ]
