# Generated by Django 3.2.8 on 2021-11-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_rename_ready_for_payment_bio_iitg_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='razorpay_order_id',
        ),
        migrations.AddField(
            model_name='bio',
            name='selected_oral',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
