# Generated by Django 3.2.8 on 2021-11-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_auto_20211120_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='link',
            field=models.URLField(default=''),
        ),
    ]
