# Generated by Django 3.2.8 on 2021-11-06 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20211106_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='cat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='team.cat'),
        ),
    ]
