# Generated by Django 3.2.8 on 2021-11-06 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20211106_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='cat',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='team.cat'),
        ),
    ]
