# Generated by Django 3.2.8 on 2021-11-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_alter_team_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='position',
            name='subtitle',
            field=models.CharField(default='', max_length=150),
        ),
    ]
