# Generated by Django 3.2.8 on 2021-11-05 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_bio_event2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bio',
            old_name='paid',
            new_name='ready_for_payment',
        ),
    ]
