# Generated by Django 3.2.8 on 2021-11-07 11:36

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0004_alter_bio_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', ckeditor.fields.RichTextField()),
                ('fee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopBio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, default=0, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('dept', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='members.dept')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ManyToManyField(blank=True, null=True, to='members.Workshop')),
            ],
        ),
    ]
