# Generated by Django 3.2.8 on 2021-11-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_alter_bio_event2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='abstract',
            field=models.FileField(upload_to='content_file_name'),
        ),
    ]
