# Generated by Django 3.2.8 on 2021-11-19 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_alter_bio_abstract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bio',
            old_name='ready_for_payment',
            new_name='iitg_student',
        ),
    ]
