# Generated by Django 3.2.8 on 2021-11-06 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_team_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.cat'),
        ),
    ]
