# Generated by Django 3.2.8 on 2021-11-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_auto_20211119_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
