# Generated by Django 3.2.8 on 2021-10-31 16:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pic', models.ImageField(upload_to='event')),
                ('subtitle', models.CharField(max_length=50)),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
