# Generated by Django 4.1.5 on 2023-01-10 14:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_speaker"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstituteSpeaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("subtitle", ckeditor.fields.RichTextField()),
                ("pic", models.ImageField(upload_to="institute")),
                ("content", ckeditor.fields.RichTextField()),
            ],
        ),
    ]
